version: 2.1

jobs:
  sonarqube_scan:
    docker:
      - image: circleci/python:3.8  # Use the appropriate Docker image for your language
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            # For a Node.js project
            # npm install

            # For a Java project (replace with the necessary steps for your project)
            curl -sS https://getcomposer.org/installer | php
            composer install  # This is only needed if you're using PHP. If not, remove this.
      - run:
          name: Install SonarScanner
          command: |
            curl -sS https://downloads.sonarsource.com/sonar-scanner-cli/sonar-scanner-4.6.2.2472-linux.zip -o /tmp/sonar-scanner.zip
            unzip /tmp/sonar-scanner.zip -d /opt
            export PATH=$PATH:/opt/sonar-scanner-4.6.2.2472-linux/bin
      - run:
          name: Run SonarQube Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=your_project_key \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build:
    jobs:
      - sonarqube_scan
