version: 2.1

jobs:
  sonarqube_scan:
    docker:
      - image: circleci/python:3.8  # Replace with an appropriate base image (e.g., 'circleci/php:7.4') or install PHP
    steps:
      - checkout
      - run:
          name: Install PHP
          command: |
            sudo apt-get update
            sudo apt-get install -y php php-cli php-mbstring php-xml php-curl
      - run:
          name: Install dependencies
          command: |
            curl -sS https://getcomposer.org/installer | php
            php composer.phar install
      - run:
          name: Install SonarScanner
          command: |
            curl -sS https://downloads.sonarsource.com/sonar-scanner-cli/sonar-scanner-4.6.2.2472-linux.zip -o /tmp/sonar-scanner.zip
            unzip /tmp/sonar-scanner.zip -d /opt
            export PATH=$PATH:/opt/sonar-scanner-4.6.2.2472-linux/bin
      - run:
          name: Run SonarQube Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=your_project_key \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build:
    jobs:
      - sonarqube_scan

