version: 2.1

jobs:
  sonarqube_scan:
    docker:
      - image: circleci/python:3.8  # Use the appropriate Docker image for your language
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            # For a Java project (e.g. Maven), replace this with the required steps for your language
            curl -sS https://getcomposer.org/installer | php  # Example for PHP
            composer install  # Replace this with `npm install`, `mvn install`, etc. based on your project
      - run:
          name: Install SonarScanner
          command: |
            curl -sS https://downloads.sonarsource.com/sonar-scanner-cli/sonar-scanner-4.6.2.2472-linux.zip -o sonar-scanner.zip
            unzip sonar-scanner.zip -d /opt
            export PATH=$PATH:/opt/sonar-scanner-4.6.2.2472-linux/bin
      - run:
          name: Run SonarQube Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=your_project_key \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build:
    jobs:
      - sonarqube_scan
