version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:latest

jobs:
  test-and-analyze:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: SonarQube Scan
          command: |
            npx sonar-scanner \
              -Dsonar.projectKey=your_project_key \
              -Dsonar.organization=your_organization_key \
              -Dsonar.sources=. \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  test_and_analyze:
    jobs:
      - test-and-analyze
